// Generated by: gen
// TypeWriter: slice
// Directive: +gen on *Attachment

package gobacklog

import (
	"errors"
	"math/rand"
)

// Sort implementation is a modification of http://golang.org/pkg/sort/#Sort
// Copyright 2009 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found at http://golang.org/LICENSE.

// AttachmentSlice is a slice of type *Attachment. Use it where you would use []*Attachment.
type AttachmentSlice []*Attachment

// Where returns a new AttachmentSlice whose elements return true for func. See: http://clipperhouse.github.io/gen/#Where
func (rcv AttachmentSlice) Where(fn func(*Attachment) bool) (result AttachmentSlice) {
	for _, v := range rcv {
		if fn(v) {
			result = append(result, v)
		}
	}
	return result
}

// Count gives the number elements of AttachmentSlice that return true for the passed func. See: http://clipperhouse.github.io/gen/#Count
func (rcv AttachmentSlice) Count(fn func(*Attachment) bool) (result int) {
	for _, v := range rcv {
		if fn(v) {
			result++
		}
	}
	return
}

// SortBy returns a new ordered AttachmentSlice, determined by a func defining ‘less’. See: http://clipperhouse.github.io/gen/#SortBy
func (rcv AttachmentSlice) SortBy(less func(*Attachment, *Attachment) bool) AttachmentSlice {
	result := make(AttachmentSlice, len(rcv))
	copy(result, rcv)
	// Switch to heapsort if depth of 2*ceil(lg(n+1)) is reached.
	n := len(result)
	maxDepth := 0
	for i := n; i > 0; i >>= 1 {
		maxDepth++
	}
	maxDepth *= 2
	quickSortAttachmentSlice(result, less, 0, n, maxDepth)
	return result
}

// GroupByString groups elements into a map keyed by string. See: http://clipperhouse.github.io/gen/#GroupBy
func (rcv AttachmentSlice) GroupByString(fn func(*Attachment) string) map[string]AttachmentSlice {
	result := make(map[string]AttachmentSlice)
	for _, v := range rcv {
		key := fn(v)
		result[key] = append(result[key], v)
	}
	return result
}

// GroupByInt groups elements into a map keyed by int. See: http://clipperhouse.github.io/gen/#GroupBy
func (rcv AttachmentSlice) GroupByInt(fn func(*Attachment) int) map[int]AttachmentSlice {
	result := make(map[int]AttachmentSlice)
	for _, v := range rcv {
		key := fn(v)
		result[key] = append(result[key], v)
	}
	return result
}

// GroupByBool groups elements into a map keyed by bool. See: http://clipperhouse.github.io/gen/#GroupBy
func (rcv AttachmentSlice) GroupByBool(fn func(*Attachment) bool) map[bool]AttachmentSlice {
	result := make(map[bool]AttachmentSlice)
	for _, v := range rcv {
		key := fn(v)
		result[key] = append(result[key], v)
	}
	return result
}

// First returns the first element that returns true for the passed func. Returns error if no elements return true. See: http://clipperhouse.github.io/gen/#First
func (rcv AttachmentSlice) First(fn func(*Attachment) bool) (result *Attachment, err error) {
	for _, v := range rcv {
		if fn(v) {
			result = v
			return
		}
	}
	err = errors.New("no AttachmentSlice elements return true for passed func")
	return
}

// MaxBy returns an element of AttachmentSlice containing the maximum value, when compared to other elements using a passed func defining ‘less’. In the case of multiple items being equally maximal, the last such element is returned. Returns error if no elements. See: http://clipperhouse.github.io/gen/#MaxBy
func (rcv AttachmentSlice) MaxBy(less func(*Attachment, *Attachment) bool) (result *Attachment, err error) {
	l := len(rcv)
	if l == 0 {
		err = errors.New("cannot determine the MaxBy of an empty slice")
		return
	}
	m := 0
	for i := 1; i < l; i++ {
		if rcv[i] != rcv[m] && !less(rcv[i], rcv[m]) {
			m = i
		}
	}
	result = rcv[m]
	return
}

// MinBy returns an element of AttachmentSlice containing the minimum value, when compared to other elements using a passed func defining ‘less’. In the case of multiple items being equally minimal, the first such element is returned. Returns error if no elements. See: http://clipperhouse.github.io/gen/#MinBy
func (rcv AttachmentSlice) MinBy(less func(*Attachment, *Attachment) bool) (result *Attachment, err error) {
	l := len(rcv)
	if l == 0 {
		err = errors.New("cannot determine the Min of an empty slice")
		return
	}
	m := 0
	for i := 1; i < l; i++ {
		if less(rcv[i], rcv[m]) {
			m = i
		}
	}
	result = rcv[m]
	return
}

// Distinct returns a new AttachmentSlice whose elements are unique. See: http://clipperhouse.github.io/gen/#Distinct
func (rcv AttachmentSlice) Distinct() (result AttachmentSlice) {
	appended := make(map[*Attachment]bool)
	for _, v := range rcv {
		if !appended[v] {
			result = append(result, v)
			appended[v] = true
		}
	}
	return result
}

// DistinctBy returns a new AttachmentSlice whose elements are unique, where equality is defined by a passed func. See: http://clipperhouse.github.io/gen/#DistinctBy
func (rcv AttachmentSlice) DistinctBy(equal func(*Attachment, *Attachment) bool) (result AttachmentSlice) {
Outer:
	for _, v := range rcv {
		for _, r := range result {
			if equal(v, r) {
				continue Outer
			}
		}
		result = append(result, v)
	}
	return result
}

// Shuffle returns a shuffled copy of AttachmentSlice, using a version of the Fisher-Yates shuffle. See: http://clipperhouse.github.io/gen/#Shuffle
func (rcv AttachmentSlice) Shuffle() AttachmentSlice {
	numItems := len(rcv)
	result := make(AttachmentSlice, numItems)
	copy(result, rcv)
	for i := 0; i < numItems; i++ {
		r := i + rand.Intn(numItems-i)
		result[r], result[i] = result[i], result[r]
	}
	return result
}

// Sort implementation based on http://golang.org/pkg/sort/#Sort, see top of this file

func swapAttachmentSlice(rcv AttachmentSlice, a, b int) {
	rcv[a], rcv[b] = rcv[b], rcv[a]
}

// Insertion sort
func insertionSortAttachmentSlice(rcv AttachmentSlice, less func(*Attachment, *Attachment) bool, a, b int) {
	for i := a + 1; i < b; i++ {
		for j := i; j > a && less(rcv[j], rcv[j-1]); j-- {
			swapAttachmentSlice(rcv, j, j-1)
		}
	}
}

// siftDown implements the heap property on rcv[lo, hi).
// first is an offset into the array where the root of the heap lies.
func siftDownAttachmentSlice(rcv AttachmentSlice, less func(*Attachment, *Attachment) bool, lo, hi, first int) {
	root := lo
	for {
		child := 2*root + 1
		if child >= hi {
			break
		}
		if child+1 < hi && less(rcv[first+child], rcv[first+child+1]) {
			child++
		}
		if !less(rcv[first+root], rcv[first+child]) {
			return
		}
		swapAttachmentSlice(rcv, first+root, first+child)
		root = child
	}
}

func heapSortAttachmentSlice(rcv AttachmentSlice, less func(*Attachment, *Attachment) bool, a, b int) {
	first := a
	lo := 0
	hi := b - a

	// Build heap with greatest element at top.
	for i := (hi - 1) / 2; i >= 0; i-- {
		siftDownAttachmentSlice(rcv, less, i, hi, first)
	}

	// Pop elements, largest first, into end of rcv.
	for i := hi - 1; i >= 0; i-- {
		swapAttachmentSlice(rcv, first, first+i)
		siftDownAttachmentSlice(rcv, less, lo, i, first)
	}
}

// Quicksort, following Bentley and McIlroy,
// Engineering a Sort Function, SP&E November 1993.

// medianOfThree moves the median of the three values rcv[a], rcv[b], rcv[c] into rcv[a].
func medianOfThreeAttachmentSlice(rcv AttachmentSlice, less func(*Attachment, *Attachment) bool, a, b, c int) {
	m0 := b
	m1 := a
	m2 := c
	// bubble sort on 3 elements
	if less(rcv[m1], rcv[m0]) {
		swapAttachmentSlice(rcv, m1, m0)
	}
	if less(rcv[m2], rcv[m1]) {
		swapAttachmentSlice(rcv, m2, m1)
	}
	if less(rcv[m1], rcv[m0]) {
		swapAttachmentSlice(rcv, m1, m0)
	}
	// now rcv[m0] <= rcv[m1] <= rcv[m2]
}

func swapRangeAttachmentSlice(rcv AttachmentSlice, a, b, n int) {
	for i := 0; i < n; i++ {
		swapAttachmentSlice(rcv, a+i, b+i)
	}
}

func doPivotAttachmentSlice(rcv AttachmentSlice, less func(*Attachment, *Attachment) bool, lo, hi int) (midlo, midhi int) {
	m := lo + (hi-lo)/2 // Written like this to avoid integer overflow.
	if hi-lo > 40 {
		// Tukey's Ninther, median of three medians of three.
		s := (hi - lo) / 8
		medianOfThreeAttachmentSlice(rcv, less, lo, lo+s, lo+2*s)
		medianOfThreeAttachmentSlice(rcv, less, m, m-s, m+s)
		medianOfThreeAttachmentSlice(rcv, less, hi-1, hi-1-s, hi-1-2*s)
	}
	medianOfThreeAttachmentSlice(rcv, less, lo, m, hi-1)

	// Invariants are:
	//	rcv[lo] = pivot (set up by ChoosePivot)
	//	rcv[lo <= i < a] = pivot
	//	rcv[a <= i < b] < pivot
	//	rcv[b <= i < c] is unexamined
	//	rcv[c <= i < d] > pivot
	//	rcv[d <= i < hi] = pivot
	//
	// Once b meets c, can swap the "= pivot" sections
	// into the middle of the slice.
	pivot := lo
	a, b, c, d := lo+1, lo+1, hi, hi
	for {
		for b < c {
			if less(rcv[b], rcv[pivot]) { // rcv[b] < pivot
				b++
			} else if !less(rcv[pivot], rcv[b]) { // rcv[b] = pivot
				swapAttachmentSlice(rcv, a, b)
				a++
				b++
			} else {
				break
			}
		}
		for b < c {
			if less(rcv[pivot], rcv[c-1]) { // rcv[c-1] > pivot
				c--
			} else if !less(rcv[c-1], rcv[pivot]) { // rcv[c-1] = pivot
				swapAttachmentSlice(rcv, c-1, d-1)
				c--
				d--
			} else {
				break
			}
		}
		if b >= c {
			break
		}
		// rcv[b] > pivot; rcv[c-1] < pivot
		swapAttachmentSlice(rcv, b, c-1)
		b++
		c--
	}

	min := func(a, b int) int {
		if a < b {
			return a
		}
		return b
	}

	n := min(b-a, a-lo)
	swapRangeAttachmentSlice(rcv, lo, b-n, n)

	n = min(hi-d, d-c)
	swapRangeAttachmentSlice(rcv, c, hi-n, n)

	return lo + b - a, hi - (d - c)
}

func quickSortAttachmentSlice(rcv AttachmentSlice, less func(*Attachment, *Attachment) bool, a, b, maxDepth int) {
	for b-a > 7 {
		if maxDepth == 0 {
			heapSortAttachmentSlice(rcv, less, a, b)
			return
		}
		maxDepth--
		mlo, mhi := doPivotAttachmentSlice(rcv, less, a, b)
		// Avoiding recursion on the larger subproblem guarantees
		// a stack depth of at most lg(b-a).
		if mlo-a < b-mhi {
			quickSortAttachmentSlice(rcv, less, a, mlo, maxDepth)
			a = mhi // i.e., quickSortAttachmentSlice(rcv, mhi, b)
		} else {
			quickSortAttachmentSlice(rcv, less, mhi, b, maxDepth)
			b = mlo // i.e., quickSortAttachmentSlice(rcv, a, mlo)
		}
	}
	if b-a > 1 {
		insertionSortAttachmentSlice(rcv, less, a, b)
	}
}
